import type { BlockPrototype } from "./types";

export const blockCatalog: BlockPrototype[] = [
  {
    id: "logo",
    name: "Logo",
    category: "Identity",
    description: "A shop sign for the top of the receipt, set in your own name.",
    designNote: "Six wordmarks cut from one name — an arch, a bar, a masthead, a ticket, a badge, a block — each fitted to the paper it prints on.",
  },
  {
    id: "weather",
    name: "Daily weather",
    category: "Daily",
    description: "A useful shape of the day, not a wall of forecast numbers.",
    designNote: "The connected dayline makes morning, afternoon, and evening read as one continuous forecast.",
    sourceName: "Open-Meteo",
    sourceUrl: "https://open-meteo.com/",
  },
  {
    id: "air",
    name: "Air quality",
    category: "Daily",
    description: "AQI, particulates, UV, and one plain-language recommendation.",
    designNote: "A large AQI leads, while the threshold rail remains readable without color.",
    sourceName: "Open-Meteo · CAMS",
    sourceUrl: "https://open-meteo.com/en/docs/air-quality-api",
  },
  {
    id: "surf",
    name: "Surf window",
    category: "Daily",
    description: "Three wave windows with size, period, and direction.",
    designNote: "Reads like a compact tide card while staying honest about the marine data available. Point it at a coastal town; inland places return flat water.",
    sourceName: "Open-Meteo Marine",
    sourceUrl: "https://open-meteo.com/en/docs/marine-weather-api",
  },
  {
    id: "games",
    name: "Game board",
    category: "Live data",
    description: "Today’s fixtures and results in a tiny scoreboard.",
    designNote: "Teams get the visual weight; score and game state stay aligned at the edge.",
    sourceName: "TheSportsDB",
    sourceUrl: "https://www.thesportsdb.com/",
  },
  {
    id: "markets",
    name: "Market pulse",
    category: "Live data",
    description: "A movement-first tape for FX now and indices later.",
    designNote: "Each row combines the latest value, signed movement, and a five-point one-bit sparkline.",
    sourceName: "Frankfurter",
    sourceUrl: "https://frankfurter.dev/",
  },
  {
    id: "news",
    name: "News brief",
    category: "Live data",
    description: "Three ranked headlines with provenance and recency.",
    designNote: "A newspaper-like rank gutter keeps long headlines scannable on narrow paper.",
    sourceName: "Hacker News",
    sourceUrl: "https://github.com/HackerNews/API",
  },
  {
    id: "earthquakes",
    name: "Earthquake watch",
    category: "Live data",
    description: "The strongest recent events, led by magnitude.",
    designNote: "Magnitude acts as the symbol, removing the need for a fragile miniature map.",
    sourceName: "USGS",
    sourceUrl: "https://earthquake.usgs.gov/earthquakes/feed/",
  },
  {
    id: "agenda",
    name: "Agenda",
    category: "Daily",
    description: "A day’s appointments with a calm, narrow time gutter.",
    designNote: "Indented rules connect event titles while keeping every start time visible at a glance.",
  },
  {
    id: "departures",
    name: "Departures",
    category: "Getting around",
    description: "Upcoming trains, platforms, and delay states.",
    designNote: "The station-board rhythm uses fixed numeric columns without imitating an LED display.",
  },
  {
    id: "home",
    name: "Home pulse",
    category: "Home & life",
    description: "A compact morning or bedtime check of the house.",
    designNote: "Normal states stay quiet; the single attention state earns a heavy marker.",
  },
  {
    id: "habit",
    name: "Habit matrix",
    category: "Write-in",
    description: "A labeled weekly grid designed to finish with a pen.",
    designNote: "The left gutter names each habit; open circles invite the human to complete the artifact after printing.",
  },
  {
    id: "dailyPlan",
    name: "Daily plan",
    category: "Write-in",
    description: "Three priorities, a light schedule, and one place for the thought that matters.",
    designNote: "The page establishes hierarchy without pre-filling the day, leaving generous writing space where decisions belong.",
  },
  {
    id: "workoutLog",
    name: "Workout log",
    category: "Write-in",
    description: "A compact training table for exercises, sets, reps, and load.",
    designNote: "Dense enough to carry to the gym, with every value large enough to write while moving. Plan the exercises ahead or take it blank.",
  },
  {
    id: "weatherJournal",
    name: "Weather journal",
    category: "Write-in",
    description: "Observe morning, noon, and evening—then draw the temperature curve yourself.",
    designNote: "An empty chart turns weather from delivered data into a small act of noticing throughout the day.",
  },
  {
    id: "mealPlan",
    name: "Meal plan",
    category: "Write-in",
    description: "Breakfast, lunch, dinner, and the prep that makes them happen.",
    designNote: "Fill the meals in and it prints them; leave one empty and it prints writing lines instead. The prep strip turns intention into action.",
  },
  {
    id: "meetingNotes",
    name: "Meeting notes",
    category: "Write-in",
    description: "Decisions, actions, owners, and the parking lot on one narrow record.",
    designNote: "Privileges what changed and who owns the next move over an endless transcript. Decisions and actions can be filled ahead of time; blank rows stay for writing during.",
  },
  {
    id: "packingList",
    name: "Packing list",
    category: "Write-in",
    description: "Four useful packing zones and a final leave-the-house check.",
    designNote: "A two-column structure keeps the receipt short while the final strip protects the things most often forgotten.",
  },
  {
    id: "delivery",
    name: "Delivery route",
    category: "Getting around",
    description: "A package’s current state, ETA, and remaining stop.",
    designNote: "The checkpoint rail turns an abstract tracking status into a physical route.",
  },
  {
    id: "countdown",
    name: "Countdown",
    category: "Home & life",
    description: "A big number for something worth anticipating.",
    designNote: "The oversized day count provides delight while the milestone rail keeps it useful.",
  },
  {
    id: "checklistGroups",
    name: "Grouped list",
    category: "Write-in",
    description: "A filled checklist sorted into named groups, with a packed count.",
    designNote: "Inverted group tags let the eye jump between sections on a narrow roll without any rules or color.",
  },
];

export const prototypeCategories = ["Identity", "Daily", "Live data", "Write-in", "Getting around", "Home & life"] as const;

export function getPrototype(id: string) {
  return blockCatalog.find((prototype) => prototype.id === id);
}
